add  OutputCachePolicy support
microsoft/reverse-proxy pull request #2328
Opened 2023-11-15 09:42 UTC by witskeeper

add  `OutputCachePolicy` to RouteConfig.cs

2023-11-15 17:02 UTC, Tratcher reviewed
Please add a brief description of output caching support to the docs. You can copy timeouts or RateLimiting. Also update the TOC.
https://github.com/microsoft/reverse-proxy/tree/main/docs/docfx/articles

2023-11-15 17:02 UTC, Tratcher commented on src/ReverseProxy/Configuration/RouteConfig.cs
> +    public string? OutputCachePolicy { get; init; }
Add this to Equals and GetHashCode

2023-11-15 17:02 UTC, Tratcher commented on src/ReverseProxy/Configuration/OutputCacheConstants.cs
> +    internal const string Default = "Default";
Not needed.

2023-11-17 01:10 UTC, witskeeper commented on src/ReverseProxy/Routing/ProxyEndpointFactory.cs
> +        }
done

2023-11-17 01:10 UTC, witskeeper commented on src/ReverseProxy/Configuration/RouteConfig.cs
> +    public string? OutputCachePolicy { get; init; }
done

2023-11-17 01:10 UTC, witskeeper commented on src/ReverseProxy/Configuration/OutputCacheConstants.cs
> +    internal const string Default = "Default";
done

2023-11-17 12:53 UTC, Kahbazi commented on docs/docfx/articles/output-caching.md
> +public void ConfigureServices(IServiceCollection services)
The samples need to be change to use the minimal APIs.  (https://github.com/microsoft/reverse-proxy/pull/2327)

2023-11-17 19:48 UTC, Tratcher commented on docs/docfx/articles/output-caching.md
> +The reverse proxy can be used to output-caching requests before they are proxied to the destination servers. This can reduce load on the destination servers, add a layer of protection, and ensure con
```suggestion
The reverse proxy can be used to cache proxied responses and serve requests before they are proxied to the destination servers. This can reduce load on the destination servers, add a layer of protection, and ensure consistent policies are implemented across your applications.
```

2023-11-17 19:48 UTC, Tratcher commented on docs/docfx/articles/output-caching.md
> +No output cache is performed on requests unless enabled in the route or application configuration.
```suggestion
No output caching is performed unless enabled in the route or application configuration.
```

2023-11-18 05:02 UTC, witskeeper commented on docs/docfx/articles/output-caching.md
> +public void ConfigureServices(IServiceCollection services)
done

2023-11-20 18:44 UTC, Tratcher commented on docs/docfx/articles/output-caching.md
> +```
```suggestion
In Program.cs add the output caching middleware.

```c#
var app = builder.Build();

app.UseOutputCache();

app.MapReverseProxy();
```
```

2023-11-20 18:46 UTC, Tratcher approved these changes

2023-11-20 20:58 UTC, Tratcher requested changes
I noticed this didn't update the ConfigValidator. 

FYI there's a big refactor happening there right now that could cause conflicts. https://github.com/microsoft/reverse-proxy/pull/2293

2023-11-21 02:55 UTC, witskeeper commented
> I noticed this didn't update the ConfigValidator.
> 
> FYI there's a big refactor happening there right now that could cause conflicts. #2293

i can  update the Validator after #2293 merged .

2023-11-22 22:16 UTC, Tratcher commented
https://github.com/microsoft/reverse-proxy/pull/2293 has been merged.

2023-11-23 08:22 UTC, witskeeper commented
@larsbj1988  already add 

> #2293 has been merged.

done

2023-11-28 07:16 UTC, witskeeper commented on src/ReverseProxy/Configuration/IYarpOutputCachePolicyProvider.cs
> +// TODO: update or remove this once AspNetCore provides a mechanism to validate the OutputCache policies
done

2023-11-28 07:32 UTC, witskeeper commented on src/ReverseProxy/Configuration/IYarpOutputCachePolicyProvider.cs
> +// TODO: update or remove this once AspNetCore provides a mechanism to validate the OutputCache policies
done

2023-11-28 16:09 UTC, merged