Fix RequestHeaderXForwardedForTransform format
microsoft/reverse-proxy pull request #2348
Opened 2023-12-08 11:55 UTC by eddietisma

Fixes #2347

2023-12-08 13:15 UTC, eddietisma commented
I figured another solution might be:

```diff
private void Append(RequestTransformContext context, string? remoteIp)
{
    var existingValues = TakeHeader(context, HeaderName);
    if (remoteIp is null)
    {
        if (!string.IsNullOrEmpty(existingValues))
        {
            AddHeader(context, HeaderName, existingValues);
        }
    }
    else
    {
-       var values = StringValues.Concat(existingValues, remoteIp);
+       var values = StringValues.Concat(existingValues, remoteIp).ToList();
-       AddHeader(context, HeaderName, values);
+       AddHeader(context, HeaderName, string.Join(", ", values));
    }
}
```

Updated MR.

2023-12-09 00:03 UTC, Tratcher requested changes
Did you see this happen in a real app or were you just looking at the tests? I think you mis-understood the test code, it was just using ';' to serialize test data, production data doesn't do that.

2023-12-09 00:03 UTC, Tratcher commented on test/ReverseProxy.Tests/Transforms/RequestHeaderXForwardedForTransformTests.cs
> +    [InlineData("existing, Header", "", ForwardedTransformActions.Set, "")]
The ';' was a test artifact, not something that would have shown up in the actual output.

2023-12-11 12:04 UTC, closed without merging

2023-12-11 12:04 UTC, eddietisma commented
Yeah, a big misunderstanding from my part. It is working as expected. Sorry!