Implement header based routing
microsoft/reverse-proxy pull request #448
Opened 2020-09-29 20:07 UTC by Tratcher

(Draft for self-review)

2020-09-30 14:54 UTC, alnikola requested changes
Looks good overall besides some comments on test coverage below.

2020-09-30 14:54 UTC, alnikola commented on src/ReverseProxy/Abstractions/RouteDiscovery/Contract/ProxyMatch.cs
> +            if (headers1 != null && headers2 == null || headers1 == null && headers2 != null)
It can be simplified because we checked at line 74 that they are not equal, thus if one is null the other is guaranteed to be **not null**.
```suggestion
            if (headers1 == null || headers2 == null)
```

2020-09-30 14:54 UTC, alnikola commented on src/ReverseProxy/Abstractions/RouteDiscovery/Contract/ProxyMatch.cs
> +            }
Nullability checks can be removed if this is moved below the next `if` block.

2020-09-30 14:54 UTC, alnikola commented on src/ReverseProxy/Configuration/ConfigurationConfigProvider.cs
> +            return headers.Select(data => Convert(data)).ToArray();
Can we reduce it to the single line?
```suggestion
            return headers?.Select(data => Convert(data)).ToArray();
```

2020-09-30 14:54 UTC, alnikola commented on src/ReverseProxy/Utilities/CaseSensitiveEqualHelper.cs
> +            }
Can it be simplified if the checks are rearranged as suggested in a comment on ProxyMatch.Equals?

2020-09-30 14:54 UTC, alnikola commented on test/ReverseProxy.Tests/IntegrationTests/RoutingTests.cs
> +            response = await client.GetAsync("/");
Let's add 2 more negative cases:
1. `request.Headers.Add("header2", "value1")`
2. `request.Headers.Add("header1", null)`

2020-09-30 14:54 UTC, alnikola commented on test/ReverseProxy.Tests/IntegrationTests/RoutingTests.cs
> +    public class RoutingTests
I believe we should add tests verifying the routing match precedence order:
1. Path
2. Method
3. Host
4. Headers

2020-09-30 14:54 UTC, alnikola commented on test/ReverseProxy.Tests/IntegrationTests/RoutingTests.cs
> +
Add negative tests for multi-value headers.

2020-10-01 20:40 UTC, JamesNK commented
> Routing has some advanced performance features like INodeBuilderPolicy that we are not implementing in this first pass. They add significant complexity and it's not clear yet if they're needed for our scenarios.

The main benefit is performance. It moves logic from being executed per-request to at startup when the DFA is built.

2020-10-02 11:50 UTC, alnikola approved these changes
LGTM

2020-10-02 15:15 UTC, javiercn commented on docs/docfx/articles/header-routing.md
> +                    }
nit: I'm not going to go a lot into the design, but you could consider
```
                    new RouteHeader()
                    {
                        Name = "Header5"
                    }
```

As a way to indicate that you only care about the header being present.

2020-10-02 15:16 UTC, javiercn commented on docs/docfx/articles/header-routing.md
> +### Sceanrio 4 - Multipe Headers
nit
```suggestion
### Scenario 4 - Multipe Headers
```

2020-10-02 15:18 UTC, javiercn commented on docs/docfx/articles/header-routing.md
> +# Header Based Routing
Question:

Is there interest in capturing the header value as part of the route values?

2020-10-02 15:21 UTC, javiercn commented on src/ReverseProxy/Abstractions/RouteDiscovery/Contract/HeaderMatchMode.cs
> +        HeaderPrefix,
Is this matching the header name?

Does the case sensitivity make sense here? (I thought the docs said that the header match was case insensitive [here](https://github.com/microsoft/reverse-proxy/pull/448/files#diff-ad8d0e4b392186631caa1ee7a2f1b874R174))

2020-10-02 15:32 UTC, javiercn commented on src/ReverseProxy/Service/Config/RuntimeRouteBuilder.cs
> +                        new HeaderMetadata(header.Name, header.Values, header.Mode, header.CaseSensitive));
nit: The `CaseSensitive` name tripped me off, maybe you could name it differently, like "Casing" with an enum instead of a bool, `IsCaseSensitive` or `CaseSensitivity`

2020-10-02 15:38 UTC, Tratcher commented on docs/docfx/articles/header-routing.md
> +# Header Based Routing
Not that I know of, at least not for the simple matching patterns supported so far. I expect that's something you'd want when using a pattern matching syntax like paths do.

2020-10-02 15:41 UTC, Tratcher commented on src/ReverseProxy/Abstractions/RouteDiscovery/Contract/HeaderMatchMode.cs
> +        HeaderPrefix,
No, its matching a prefix of the header value, optional case sensitivity still makes sense there.

2020-10-02 15:41 UTC, javiercn commented on src/ReverseProxy/Service/Routing/HeaderMatcherPolicy.cs
> +                            var requestHeaderValue = requestHeaderValues.ToString();
Is this going to allocate a new string?

2020-10-02 15:43 UTC, Tratcher commented on src/ReverseProxy/Service/Routing/HeaderMatcherPolicy.cs
> +                            var requestHeaderValue = requestHeaderValues.ToString();
No, it just forces the type conversion from a StringValue of array length 1 to a string.

2020-10-02 15:44 UTC, Tratcher commented on src/ReverseProxy/Service/Config/RuntimeRouteBuilder.cs
> +                        new HeaderMetadata(header.Name, header.Values, header.Mode, header.CaseSensitive));
`bool IsCaseSensitive` would work.

2020-10-02 15:47 UTC, javiercn commented on src/ReverseProxy/Service/Routing/HeaderMatcherPolicy.cs
> +        private class HeaderMetadataEndpointComparer : IComparer<Endpoint>
Is there really a need to disambiguate endpoints based on the casing or one endpoint being "more" specific than the other?

It feels brittle to route to A instead of B based on them having matching the same value with the only difference that one matches it exactly and the other one does not. IMO it's better to not support that type of thing and throw an error indicating there is an ambiguity, the current behavior can lead to very subtle hard to detect errors.

2020-10-02 15:48 UTC, Tratcher commented on docs/docfx/articles/header-routing.md
> +                    }
I considered it but it seemed error prone, too easy to accidentally leave out the value. By using the mode the intent is a lot clearer and we can provide better argument validation and errors.

2020-10-02 15:56 UTC, Tratcher commented on src/ReverseProxy/Service/Routing/HeaderMatcherPolicy.cs
> +        private class HeaderMetadataEndpointComparer : IComparer<Endpoint>
Fair, we can scale this back to only consider the number of header rules.

2020-10-02 16:00 UTC, javiercn commented on docs/docfx/articles/header-routing.md
> +# Header Based Routing
The scenario that I'm thinking of is transforming an outgoing request based on the contents of a header. For example a request to /api with the version on the header to /v1/api in the downstream request, but not sure if that's a scenario.

2020-10-02 16:11 UTC, Tratcher commented on docs/docfx/articles/header-routing.md
> +# Header Based Routing
Since we primarily support an exact match against the header, a given route already knows what the value is and can hard code that into the transform for that route.

This does get more interesting for the Exists or Prefix modes where the value is more fluid, but I'd wait to pursue that until we have some specific requirements for it.

2020-10-02 16:42 UTC, javiercn commented on docs/docfx/articles/header-routing.md
> +# Header Based Routing
Fair enough

2020-10-02 16:46 UTC, javiercn approved these changes
Looks great!

2020-10-02 16:47 UTC, javiercn commented on docs/docfx/articles/header-routing.md
> +                    }
Fair enough, I think it'll be more common to require a value than just the header being present.

2020-10-02 17:15 UTC, JamesNK commented on src/ReverseProxy/Service/Routing/HeaderMatcherPolicy.cs
> +                var metadataList = candidates[i].Endpoint.Metadata.GetOrderedMetadata<IHeaderMetadata>();
I’m not sure about this. I believe all our other matcher policies have metadata that contains all required info.

Using GetOrderedMetadata means that an action couldn’t override the behavior of a controller.

I’m reviewing on my phone so it is hard to check :smile:

2020-10-02 17:25 UTC, Tratcher commented on src/ReverseProxy/Service/Routing/HeaderMatcherPolicy.cs
> +                var metadataList = candidates[i].Endpoint.Metadata.GetOrderedMetadata<IHeaderMetadata>();
That's true, they would be cumulative ANDs.

We looked at trying to define multiple header matches in one rule/metadata but it was very complicated/nested. Other metadata like Method, Host, etc. are simple lists of strings, not complex rules with multiple options each. Note the Authorize attribute is the other one that uses GetOrderedMetadata and it's cumulative, sortof.
https://github.com/dotnet/aspnetcore/blob/1c27ba1bbdc3aac6b483965eb7150011a97ed5b7/src/Security/Authorization/Policy/src/AuthorizationMiddleware.cs#L47-L48

2020-10-02 17:28 UTC, javiercn commented on src/ReverseProxy/Service/Routing/HeaderMatcherPolicy.cs
> +                var metadataList = candidates[i].Endpoint.Metadata.GetOrderedMetadata<IHeaderMetadata>();
The metadata that you put in place could be a list of rules? I'm not sure how clean that would be. HttpMethodMetadata does that I think.

2020-10-02 17:29 UTC, javiercn commented on src/ReverseProxy/Service/Routing/HeaderMatcherPolicy.cs
> +                var metadataList = candidates[i].Endpoint.Metadata.GetOrderedMetadata<IHeaderMetadata>();
We will have to think about the semantics here when there are more than one of these things applied to a controller and an action.

2020-10-02 17:41 UTC, Tratcher commented on src/ReverseProxy/Service/Routing/HeaderMatcherPolicy.cs
> +                var metadataList = candidates[i].Endpoint.Metadata.GetOrderedMetadata<IHeaderMetadata>();
> The metadata that you put in place could be a list of rules? I'm not sure how clean that would be. HttpMethodMetadata does that I think.

Yeah, HttpMethodMetadata is a simple `string[]`. We'd need a `RouteHeader[]` and I don't see how you'd be able to build that in a single attribute.

2020-10-02 17:43 UTC, javiercn commented on src/ReverseProxy/Service/Routing/HeaderMatcherPolicy.cs
> +                var metadataList = candidates[i].Endpoint.Metadata.GetOrderedMetadata<IHeaderMetadata>();
We separate the metadata from the attribute, and we combine them at the MVC level.

Endpoint metadata != Controller/Action metadata

2020-10-02 17:44 UTC, Tratcher commented on src/ReverseProxy/Service/Routing/HeaderMatcherPolicy.cs
> +                var metadataList = candidates[i].Endpoint.Metadata.GetOrderedMetadata<IHeaderMetadata>();
Headers are also something you can have more than one of, so it makes more sense for them to be cumulative unless it's for the same header name?
```
[Header("h1", "v1")]
Controller
{
  [Header("h2", "v2")]
  Action
}
```

2020-10-02 17:44 UTC, javiercn commented on src/ReverseProxy/Service/Routing/HeaderMatcherPolicy.cs
> +                var metadataList = candidates[i].Endpoint.Metadata.GetOrderedMetadata<IHeaderMetadata>();
Just to be clear, I'm not complaining about anything specific. I don't know what the correct behavior will be and we will cross that bridge when we get there.

2020-10-02 17:45 UTC, javiercn commented on src/ReverseProxy/Service/Routing/HeaderMatcherPolicy.cs
> +                var metadataList = candidates[i].Endpoint.Metadata.GetOrderedMetadata<IHeaderMetadata>();
> Headers are also something you can have more than one of, so it makes more sense for them to be cumulative unless it's for the same header name?
> 
> ```
> [Header("h1", "v1")]
> Controller
> {
>   [Header("h2", "v2")]
>   Action
> }
> ```

I'm happy if you come up with a proposal and we take it from there. I don't think we should block on this at the moment, just make a note for the future.

2020-10-02 18:04 UTC, samsp-msft commented
> * Headers are lower priority matches than paths, methods, and hosts. One unanticipated side effect of this I saw was if one route specifies methods and another specifies headers, the methods route will always win as more specific. The headers check only comes into play if the higher priority checks are equal.

Is there a way to add a manual priority/weight to routes to bypass the default ordering. For example if I want all requests with a debug header to go to a specific destination, could I flag that rule in some way to push it to the top of the stack?

2020-10-02 18:16 UTC, javiercn commented
> Is there a way to add a manual priority/weight to routes to bypass the default ordering. For example if I want all requests with a debug header to go to a specific destination, could I flag that rule in some way to push it to the top of the stack?

If you are able to specify the route order explicitly that takes precedence over anything else. Routing supports that, I'm not sure if YARP exposes it, but it would be something good to expose.

2020-10-02 18:38 UTC, Tratcher commented
Yes, YARP exposes the Order option on routes.

2020-10-02 21:13 UTC, Kahbazi commented on docs/docfx/articles/header-routing.md
> +### Scenario 4 - Multipe Headers
```suggestion
### Scenario 4 - Multiple Headers
```

2020-10-02 22:11 UTC, Tratcher commented on src/ReverseProxy/Service/Routing/HeaderMatcherPolicy.cs
> +                var metadataList = candidates[i].Endpoint.Metadata.GetOrderedMetadata<IHeaderMetadata>();
> Endpoint metadata != Controller/Action metadata

That's a good point. I've re-worked it to use a single metadata type with a list. We'll worry about how to generate that list for MVC later.

2020-10-05 18:23 UTC, halter73 requested changes

2020-10-05 18:23 UTC, halter73 commented on src/ReverseProxy/Utilities/CaseInsensitiveEqualHelper.cs
> +            if (list1 == null || list2 == null)
Much nicer!

2020-10-05 19:17 UTC, Tratcher commented on docs/docfx/articles/header-routing.md
> +Indicates if the value match should be performed as case sensitive or insensitive. The default is `false`, insensitive.
I don't know. It's more of an escape hatch for people, I'm not sure how much it will get used.

2020-10-05 19:21 UTC, Tratcher commented on src/ReverseProxy/Abstractions/RouteDiscovery/Contract/HeaderMatchMode.cs
> +        // ValuePrefix,
We're not doing these right now, we'll wait for feedback first. I left them here as examples of possible future values.

I don't know about Contains, it has mixed connotations from string.Contains and ICollection.Contains, we'd want the latter.

2020-10-05 19:22 UTC, Tratcher commented on src/ReverseProxy/Abstractions/RouteDiscovery/Contract/RouteHeader.cs
> +        internal static bool Equals(RouteHeader header1, RouteHeader header2)
To simplify the calling code when either value might be null.

2020-10-05 19:43 UTC, Tratcher commented on docs/docfx/articles/header-routing.md
> +A convenience overload of `Values` for the common single value scenario. `Values` is preferred if specified.
It is in the sample configuration for route1. 
```
            {
              "Name": "header1",
              "Value": "value1"
            }
```

I expect this to be the most common usage so it seemed to warrant special casing. This is the kind of thing we had in mind when we split the config model from the code mode. I can cut it for now and revisit when we look at the overall usability of the config model.

2020-10-05 19:47 UTC, halter73 approved these changes

2020-10-05 23:39 UTC, Tratcher commented
/azp run

2020-10-06 18:08 UTC, merged