Service Fabric integration for route discovery should support transforms
microsoft/reverse-proxy pull request #532
Opened 2020-11-11 03:37 UTC by akanieski

See #528 for more complete summary of the work represented on this PR.

2020-11-11 03:41 UTC, Tratcher commented
Blocked on #257.

2020-11-11 03:43 UTC, akanieski commented
> Blocked on #257.

Was it better to create a new PR for this? Or should I fold it into 257? Not sure what's standard procedure.

2020-11-11 03:55 UTC, Tratcher commented
We plan to merge #257 soon, so a separate PR is better, but you will have to wait for that one to merge and then rebase.

2020-11-26 13:33 UTC, alnikola commented
@akanieski The main SF PR has been merged. Could you please tell me if you are going to continue working on this one?

2020-11-30 12:11 UTC, alnikola approved these changes
LGTM

2020-11-30 17:00 UTC, Tratcher requested changes

2020-11-30 17:00 UTC, Tratcher commented on test/ReverseProxy.ServiceFabric.Tests/ServiceDiscovery/Util/LabelsParserTests.cs
> +                        new Dictionary<string, string>{
```suggestion
                        new Dictionary<string, string>
                        { 
```

2020-11-30 17:00 UTC, Tratcher commented on test/ReverseProxy.ServiceFabric.Tests/ServiceDiscovery/Util/LabelsParserTests.cs
> +                        new Dictionary<string, string>{
```suggestion
                        new Dictionary<string, string>
                        { 
```

2020-11-30 17:03 UTC, alnikola commented on src/ReverseProxy.ServiceFabric/ServiceDiscovery/Util/LabelsParser.cs
> +                            transforms.Add(transformName, new Dictionary<string, string>());
We are currently using `Ordinal` everywhere in SF integration because it started with label keys being case sensitive. Do you really think it should be `OrdinalIgnoreCase` here?

2020-11-30 17:06 UTC, Tratcher commented on src/ReverseProxy.ServiceFabric/ServiceDiscovery/Util/LabelsParser.cs
> +                    else if (kvp.Key.StartsWith($"{thisRoutePrefix}.Transforms.", StringComparison.Ordinal))
https://github.com/microsoft/reverse-proxy/issues/586

2020-11-30 17:10 UTC, Tratcher commented on src/ReverseProxy.ServiceFabric/ServiceDiscovery/Util/LabelsParser.cs
> +                            transforms.Add(transformName, new Dictionary<string, string>());
Pretty much all of config and transforms are OrdinalIgnoreCase in other providers, I don't see why SF would be different.
https://github.com/microsoft/reverse-proxy/blob/23a572bc0b54c4975869786d5e003159efdc2cb9/src/ReverseProxy/Configuration/ConfigurationConfigProvider.cs#L188

That said, if all of SF is currently Ordinal then we don't need to change it in this PR. Do we have a follow-up issue for label case sensitivity? If not please make one.

2020-11-30 17:42 UTC, alnikola commented on src/ReverseProxy.ServiceFabric/ServiceDiscovery/Util/LabelsParser.cs
> +                            transforms.Add(transformName, new Dictionary<string, string>());
Yes, there is an issue for this #553.

2020-12-01 18:06 UTC, akanieski commented on src/ReverseProxy.ServiceFabric/ServiceDiscovery/Util/LabelsParser.cs
> +                        transforms[transformName].Add(propertyName, kvp.Value);
A thrown exception in this code path would fail back to the catch block on [Discoverer line 138](https://github.com/microsoft/reverse-proxy/blob/8a2a790962ff44a85dab228472757b1f3189fb0f/src/ReverseProxy.ServiceFabric/ServiceDiscovery/Discoverer.cs#L138). In general, any exception in BuildRoutes causes the service to not be included in the snapshot update. Which would remove previous working configurations.

Two concerns that jump out to me:
- Should we just report and ignore such a configuration problem? Or should we continue to let it skip over the service if an exception like this occurs?
- If we fail the service, should it allow the previous configuration for that service to remain? My guess would be no. Just tossing it out there.

2020-12-01 18:14 UTC, akanieski commented on src/ReverseProxy.ServiceFabric/ServiceDiscovery/Util/LabelsParser.cs
> +        private static readonly Regex _allowedPropertyNamesRegex = new Regex("^[a-zA-Z0-9_-]+$");
The `_allowedTransformsNameRegex` locks you in on the `.[0].` format you mentioned before. 

The `_allowedPropertyNamesRegex` is sort of pointless actually considering there is a finite number of acceptable values that start on [TransformBuilder.cs Ln 45](https://github.com/microsoft/reverse-proxy/blob/8a2a790962ff44a85dab228472757b1f3189fb0f/src/ReverseProxy/Service/Config/TransformBuilder.cs#L45).

Would you prefer I pull those values into a static class with a string property for each available option so that we can cross reference when validating valid transform configuration?

2020-12-01 18:28 UTC, Tratcher commented on src/ReverseProxy.ServiceFabric/ServiceDiscovery/Util/LabelsParser.cs
> +        private static readonly Regex _allowedPropertyNamesRegex = new Regex("^[a-zA-Z0-9_-]+$");
> The `_allowedTransformsNameRegex` locks you in on the `.[0].` format you mentioned before.

Please add that comment to the code.

> The _allowedPropertyNamesRegex is sort of pointless actually considering there is a finite number of acceptable values that start on TransformBuilder.cs Ln 45.

The labels parser doesn't need to validate individual transforms, the config validator will handle that later. You can remove this regex check.

2020-12-04 16:13 UTC, akanieski commented on src/ReverseProxy.ServiceFabric/ServiceDiscovery/Util/LabelsParser.cs
> +                        transforms[transformName].Add(propertyName, kvp.Value);
Actually, it looks like we would catch this in the step where we parse the service extension xml. It will throw if it finds a duplicate key. In the case of an existing transform property name it would throw as it would be caught earlier. There is a test to confirm that throw happens. `GetExtensionLabels_DuplicatedLabelKeysInManifest_ShouldThrowException`.

2020-12-08 00:16 UTC, Tratcher approved these changes

2020-12-08 00:16 UTC, merged

2020-12-08 00:16 UTC, Tratcher commented
Thanks