Creating a basic sample with annotations
microsoft/reverse-proxy pull request #761
Opened 2021-02-18 23:50 UTC by samsp-msft

2021-02-18 23:55 UTC, samsp-msft commented on samples/Basic YARP Sample/MyStartup.cs
> +            // TODO: should this be removed: app.UseAuthorization();
Do we need this in the sample?

2021-02-18 23:55 UTC, samsp-msft commented on samples/Basic YARP Sample/Program.cs
> +            var myHostBuilder = Host.CreateDefaultBuilder(args);
This is a bit more verbose, but is less alien to somebody new than the .Build().Run() that is usually here.

2021-02-18 23:55 UTC, samsp-msft commented on samples/Basic YARP Sample/Program.cs
> +            myHostBuilder.ConfigureWebHostDefaults(webHostBuilder =>
I am in 2 minds about the lambda verses a second method, both are a bit odd from a 101 standpoint.

2021-02-18 23:55 UTC, samsp-msft commented on samples/Basic YARP Sample/appsettings.json
> +  // Base URLs the server listens on, must be configured independently of the routes below
Our config files support comments, so lets use them to explain what is going on.

2021-02-18 23:55 UTC, samsp-msft commented on samples/Basic YARP Sample/appsettings.json
> +  "Urls": [
Not strictly necessary, but makes it more obvious how to change what the server is listening on.

2021-02-18 23:55 UTC, samsp-msft commented on samples/Basic YARP Sample/appsettings.json
> +      // Uncomment to hide diagnostic messages
Kind of nice to have this as on by default as it shows what is going on with the proxy, and why things may fail.

2021-02-19 00:00 UTC, samsp-msft commented
@davidfowl @Tratcher - We don't have an obvious basic starting point. The goal is to make it seem as less alien as possible for people who are not deeply immersed in the ASP.NET core ecosystem.

2021-02-19 00:42 UTC, Tratcher reviewed
The goal makes sense, especially with the extra comments you added. A few of the changes like the Startup class name seem more likely to add confusion than remove it.

2021-02-19 00:42 UTC, Tratcher commented on samples/Basic YARP Sample/MyStartup.cs
> +    public class MyStartup
Startup is a very standard convention in AspNet. Changing it is likely to cause confusion when comparing to other samples.
```suggestion
    public class Startup
```

2021-02-19 00:42 UTC, Tratcher commented on samples/Basic YARP Sample/MyStartup.cs
> +    // Provides a configuration for the kestrel server with reverse proxy middleware
```suggestion
    // Sets up the ASP.NET application with the reverse proxy enabled.
```

2021-02-19 00:42 UTC, Tratcher commented on samples/Basic YARP Sample/MyStartup.cs
> +        // the web server via services in the DI container.
```suggestion
        // the web application via services in the DI container.
```

2021-02-19 00:42 UTC, Tratcher commented on samples/Basic YARP Sample/MyStartup.cs
> +            ProxyBuilder.LoadFromConfig(Configuration.GetSection("ReverseProxy"));
Style:
```suggestion
            var proxyBuilder = services.AddReverseProxy();
            // Initialize the reverse proxy from the "ReverseProxy" section of configuration
            proxyBuilder.LoadFromConfig(Configuration.GetSection("ReverseProxy"));
```

2021-02-19 00:42 UTC, Tratcher commented on samples/Basic YARP Sample/MyStartup.cs
> +        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline for each request
```suggestion
        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline that handles requests
```

2021-02-19 00:42 UTC, Tratcher commented on samples/Basic YARP Sample/MyStartup.cs
> +            // TODO: should this be removed: app.UseAuthorization();
If they enable auth on any of their routes they'll need this, but that's covered in the docs.

2021-02-19 00:42 UTC, Tratcher commented on samples/Basic YARP Sample/appsettings.json
> +    // Defines the routes the proxy will listen on
This is ambiguous with the urls given above.
```suggestion
    // Routes tell the proxy which requests to forward.
```

2021-02-19 00:42 UTC, Tratcher commented on samples/Basic YARP Sample/appsettings.json
> +          }
They won't have these servers, do we want examples that will fail?

2021-02-19 00:42 UTC, Tratcher commented on samples/Basic YARP Sample/appsettings.json
> +    // Defines the clusters that routes can route to
```suggestion
    // Clusters tell the proxy where to forward requests and how.
```

2021-02-19 00:42 UTC, Tratcher commented on samples/Basic YARP Sample/appsettings.json
> +      "cluster2": {
Show load balancing config or session affinity as a sample cluster option?

2021-02-19 00:42 UTC, Tratcher commented on samples/Basic YARP Sample/Program.cs
> +            var myHostBuilder = Host.CreateDefaultBuilder(args);
FYI There's tooling for EF and testing that depend on the CreateHostBuilder pattern.

Can you keep the CreateHostBuilder method? The parts you've expanded were already in Main.

2021-02-19 00:42 UTC, Tratcher commented on samples/Basic YARP Sample/MyStartup.cs
> +            // Configure EndPoints to use the reverse proxy
```suggestion
            // Register the reverse proxy routes
```

2021-02-19 00:42 UTC, Tratcher commented on samples/Basic YARP Sample/appsettings.json
> +  ],
Urls is one string with semicolons, not an array.
```suggestion
  "Urls": "http://localhost:5000;https://localhost:5001",
```

2021-02-19 00:42 UTC, Tratcher commented on samples/Basic YARP Sample/Properties/launchSettings.json
> +      "launchBrowser": true,
With the Urls set in the appsettings.json rather than the launchSettings.json, the tooling doesn't know which url to launch. I don't think this applies to the command line scenarios anyways.
```suggestion
      "launchBrowser": false,
```

2021-02-19 00:44 UTC, Tratcher commented on samples/Basic YARP Sample/Basic YARP Sample.csproj
> +<Project Sdk="Microsoft.NET.Sdk.Web">
Are spaces in the folder and project name a good idea? They tend to cause havoc on the command line.

2021-02-19 06:29 UTC, davidfowl commented on samples/Basic YARP Sample/Program.cs
> +            var myHostBuilder = Host.CreateDefaultBuilder(args);
Why would they use EF Core in the YARP process?

2021-02-19 06:34 UTC, samsp-msft commented on samples/Basic YARP Sample/Program.cs
> +            var myHostBuilder = Host.CreateDefaultBuilder(args);
+1 - also that's less likely to be the customer for this type of sample. Sure somebody could be doing an advanced proxy that is pulling routes from a db, but that customer is more likely to use one of the other samples.

2021-02-19 06:37 UTC, samsp-msft commented on samples/Basic YARP Sample/Basic YARP Sample.csproj
> +    <PackageReference Include="Microsoft.ReverseProxy" Version="1.0.0-preview.*" />
Do we have a todo in the release checklist to update this in the samples? If so then fine.
Also there is so little in this sample that is likely to conflict.

2021-02-19 06:38 UTC, samsp-msft commented on samples/Basic YARP Sample/MyStartup.cs
> +    public class MyStartup
IMHO both are a really bad name, as its not really startup, its more of a configuration. ServiceInit or something would be better.

2021-02-19 06:44 UTC, samsp-msft commented on samples/Basic YARP Sample/appsettings.json
> +  ],
I tried a single string and it threw, I think logically its an array. The array works!.

2021-02-19 07:01 UTC, samsp-msft commented on samples/Basic YARP Sample/Properties/launchSettings.json
> +  "$schema": "http://json.schemastore.org/launchsettings.json",
If launchsettings can have a schema file - does one exist for asp.net core, or can/should we create one for YARP that has all of the config options in it so that those using VS (and possibly code) get intellisense?

2021-02-19 18:19 UTC, samsp-msft commented on samples/Basic YARP Sample/appsettings.json
> +          }
What would you suggest instead?

2021-02-19 22:07 UTC, Tratcher commented on samples/Basic YARP Sample/Basic YARP Sample.csproj
> +    <PackageReference Include="Microsoft.ReverseProxy" Version="1.0.0-preview.*" />
Our in-repo samples don't use packages references, they use project references. We do have TODO in the release check-list to update the getting-started guide that uses a versioned package reference. This sample could be added to the list.
https://microsoft.github.io/reverse-proxy/articles/getting_started.html
https://github.com/microsoft/reverse-proxy/blob/main/docs/operations/Release.md#consume-nupkg

Long term I expect this would be better off in its own repo so people can acquire it directly.

2021-02-19 22:08 UTC, Tratcher commented on samples/Basic YARP Sample/MyStartup.cs
> +    public class MyStartup
Granted, but let's stick with the standards where can.

2021-02-19 22:11 UTC, Tratcher commented on samples/Basic YARP Sample/appsettings.json
> +          }
How about `https://example.com/foo` and ``https://example.com/bar`?

2021-02-19 22:27 UTC, Tratcher commented on samples/Basic YARP Sample/appsettings.json
> +  ],
I just confirmed `"Urls": "https://localhost:5004;http://localhost:5002",` works. When I try the array format you have here it's ignored and it uses the default values (which also happen to be 5000 and 5001).

You're right an array would make more sense in the JSON scenario, but this key was designed mainly for use on command line and environment variables.

2021-02-19 22:31 UTC, Tratcher commented on samples/Basic YARP Sample/Properties/launchSettings.json
> +  "$schema": "http://json.schemastore.org/launchsettings.json",
That's a good question, I know we just added a schema for appsettings.json. If we need to create one then that should be owned by ASP.NET, not YARP. I'll file an issue in aspnetcore.

2021-02-19 22:32 UTC, Tratcher commented on samples/Basic YARP Sample/Properties/launchSettings.json
> +  "$schema": "http://json.schemastore.org/launchsettings.json",
Oh, this is already a registered schema...
https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/launchsettings.json

2021-02-19 22:49 UTC, samsp-msft commented on samples/Basic YARP Sample/Properties/launchSettings.json
> +  "$schema": "http://json.schemastore.org/launchsettings.json",
How can we get appsettings.json schema to include YARP?

2021-02-19 22:54 UTC, Tratcher commented on samples/Basic YARP Sample/Properties/launchSettings.json
> +  "$schema": "http://json.schemastore.org/launchsettings.json",
That would take a contribution to [here](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/appsettings.json). That might be worth it when yarp becomes more stable, until then maybe we should provide our own?

2021-02-19 22:55 UTC, Tratcher commented on samples/Basic YARP Sample/Properties/launchSettings.json
> +  "$schema": "http://json.schemastore.org/launchsettings.json",
That seems like something we'd invest in when working on the pre-built exe scenario.

2021-02-19 23:12 UTC, Tratcher commented on samples/BasicYarpSample/appsettings.json
> +            "Address": "https://bing.com:20000"
```suggestion
            "Address": "https://bing.com"
```

2021-02-22 11:59 UTC, karelz requested changes

2021-02-22 11:59 UTC, karelz commented on samples/BasicYarpSample/Program.cs
> +            // Create a Kestrel web server, and tell it to use the MyStartup class
```suggestion
            // Create a Kestrel web server, and tell it to use the Startup class
```

2021-02-22 11:59 UTC, karelz commented on samples/BasicYarpSample/appsettings.json
> +        // matches /something/* and routes to 2 localhost addresses
```suggestion
        // matches /something/* and routes to 2 external addresses
```

2021-02-23 00:27 UTC, samsp-msft commented on samples/Basic YARP Sample/Basic YARP Sample.csproj
> +    <PackageReference Include="Microsoft.ReverseProxy" Version="1.0.0-preview.*" />
Added to the release instructions

2021-02-23 00:47 UTC, Tratcher approved these changes
Let's discuss the other samples in sync-up tomorrow.

2021-02-23 14:10 UTC, karelz approved these changes
Formatting, casing and spelling changes only

2021-02-23 14:10 UTC, karelz commented on samples/BasicYarpSample/README.md
> +That algorithm is best with more than 2 choices, but shows how to specify an algorithm in config.
```suggestion
    As its a more specific route, it will match before the route above, even though it is listed second. 
    This routes to a cluster named *cluster2* with 2 destinations. 
    It will load balance between those 2 destinations using a Power of two choices algorithm. 
    That algorithm is best with more than 2 choices, but shows how to specify an algorithm in config.
```

2021-02-23 14:10 UTC, karelz commented on samples/BasicYarpSample/README.md
> +* [Properties/launchsettings.json](Properties/launchsettings.json) - a configuration file use by Visual Studio to tell it how to start the app when debugging.
```suggestion
- [BasicYarpSample.csproj](BasicYarpSample.csproj) - A C# project file (conceptually similar to a make file) that tells it to target the .NET 5 runtime, and to reference the proxy library from [nuget](https://www.nuget.org/packages/Microsoft.ReverseProxy/) (.NET's package manager).
- [Program.cs](Program.cs) - Provides the main entrypoint for .NET which uses an WebHostBuilder to initialize the Kestrel server which listens for http requests. Typically, this file does not need to be modified for any proxy scenarios.
- [Startup.cs](Startup.cs) - Provides a class that is used to configure and control how http requests are handled by Kestrel. In this sample, it does the bare minimum of:
  - Adding proxy functionality to the service.
  - Specifying that the proxy configuration will come from the config file (altrenatively it could be specified via code).
  - Telling Kestrel to use its routing service, to register the routes from YARP into its routing table, and use YARP to handle those requests.
- [appsettings.json](appsettings.json) - The configuration file for the .NET app, including sections for Kestrel, logging and the YARP proxy configuration. 
- [Properties/launchsettings.json](Properties/launchsettings.json) - A configuration file used by Visual Studio to tell it how to start the app when debugging.
```

2021-02-23 14:10 UTC, karelz commented on samples/BasicYarpSample/README.md
> +* Download and install Visual Studio from https://visualstudio.microsoft.com/ - versions are available for Windows & MacOS including a free community edition.
```suggestion
* Download and install Visual Studio from https://visualstudio.microsoft.com/ - versions are available for Windows and MacOS, including a free community edition.
```

2021-02-23 14:10 UTC, karelz commented on samples/BasicYarpSample/README.md
> +     eg ```dotnet run ../SampleServer --Urls "http://localhost:10000;https://localhost:10010"```
```suggestion
- Change the ports the proxy listens on using the URLs property in configuration or on the command line.
- Change the routes and destinations used by the proxy.
- A web server sample is available in the [SampleServer](../SampleServer) folder. It will output the request headers as part of the response body so they can be examined with a browser.
    - The URLs the server listens to can be changed on the command line, so that multiple instances can be run. 
     eg ```dotnet run ../SampleServer --Urls "http://localhost:10000;https://localhost:10010"```
```

2021-02-23 17:21 UTC, Tratcher reviewed
Clarifying terms.

2021-02-23 17:21 UTC, Tratcher commented on samples/BasicYarpSample/README.md
> +The proxy server is implemented as middleware for the ASP.NET Core "Kestrel" web server. Kestrel provides the front end for the proxy, which listens for http requests, and then passes them to the pro
```suggestion
The proxy server is implemented a plugin component for ASP.NET Core applications. ASP.NET Core servers like Kestrel provide the front end for the proxy by listening for http requests and then passing them to the proxy for paths that the proxy has registered. The proxy handles the requests by:
```

2021-02-23 17:21 UTC, Tratcher commented on samples/BasicYarpSample/README.md
> +**Note:** The destination addresses used in the sample are using DNS names rather than IP addresses, this is so that the sample can be run and used without further changes. In a typical deployment, t
There is no requirement to use IPs over host names, that's up to the deployment. I think most of our current customers use host names.

2021-02-23 17:21 UTC, Tratcher commented on samples/BasicYarpSample/README.md
> +- [Startup.cs](Startup.cs) - Provides a class that is used to configure and control how http requests are handled by Kestrel. In this sample, it does the bare minimum of:
```suggestion
- [Program.cs](Program.cs) - Provides the main entrypoint for .NET which uses an WebHostBuilder to initialize the server which listens for http requests. Typically, this file does not need to be modified for any proxy scenarios.
- [Startup.cs](Startup.cs) - Provides a class that is used to configure and control how http requests are handled by the server. In this sample, it does the bare minimum of:
```

2021-02-23 17:21 UTC, Tratcher commented on samples/BasicYarpSample/README.md
> +  - Adding proxy functionality to the service.
```suggestion
  - Adding proxy functionality to the services collection.
```

2021-02-23 17:21 UTC, Tratcher commented on samples/BasicYarpSample/README.md
> +  - Telling Kestrel to use its routing service, to register the routes from YARP into its routing table, and use YARP to handle those requests.
```suggestion
  - Telling ASP.NET to use its routing service, to register the routes from YARP into its routing table, and use YARP to handle those requests.
```

2021-02-23 17:21 UTC, Tratcher commented on samples/BasicYarpSample/README.md
> +* File change notification is used for the appsettings.config file so changes can be made on the fly.
```suggestion
* File change notification is used for the appsettings.json file so changes can be made on the fly.
```

2021-02-23 18:12 UTC, samsp-msft commented on samples/BasicYarpSample/README.md
> +**Note:** The destination addresses used in the sample are using DNS names rather than IP addresses, this is so that the sample can be run and used without further changes. In a typical deployment, t
Really?

2021-02-23 19:38 UTC, merged